name: Notify Parent Repo
on:
  push:
    branches: [main]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent repo workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PARENT_REPO_TOKEN }}
          repository: Mattheo4427/Eventy-back
          event-type: submodule-updated
          client-payload: '{"submodule": "${{ github.repository }}"}'
